version: '3'
services:
  elk-api:
    build: ./src
    volumes:
      - api-data:/usr/src/app/static
    ports:
      - "5000:5000"
    environment:
      ELASTICSEARCH_URL: http://elastic-search-service:9200
      ELASTICSEARCH_HOSTS: http://elastic-search-service:9200
    networks:
      - elastic
  elastic-search-service:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elastic-search-service
    environment:
      - node.name=elastic-search-service
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elastic-search-service
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic-search-service:9200
      ELASTICSEARCH_HOSTS: http://elastic-search-service:9200
    networks:
      - elastic

volumes:
  elastic-data:
    driver: local
  api-data:
    driver: local

networks:
  elastic:
    driver: bridge